#!/bin/env Rscript

# Calculate recombination rates for genomic windows

# Load R libraries
library(data.table)

# Load R data file for the masked SNPRC reference panel generated by the run.01.prep_for_pedigree_inconsistencies.R script
load("local_ancestry_pedigree_trios_maskedSNPRCref.Rd", verbose=T) 

# we only need the positions data frame so remove all other loaded data frames
rm(indiv_list, tracts2, trios)

# need to create a data frame of empty_windows (chrom, start, end) to calculate, for each chromosome and each window within a chromosome, the mean recombination rate for a window
wind=250000 # use 250 kb as our window size (even though our focal sites are 35 kb apart - a 35 kb window size for mean recombination rate would generate too noisy of an estimate)
positions$start <- positions$pos-(wind/2)
positions$end <- positions$pos+(wind/2)

empty_windows <- positions
rm(positions)

rcr<- NULL
for (k in 1:20) { #For each chromosome
  # load recombination rates available in Section 03_baboon-genomic-resources
  name=paste("../../03_baboon-genomic-resources/Resources/Recombination_Rates/anubisSNPRC.",k,".txt",sep="")
  fread(name) -> RCR; c(colnames(RCR)[-1],"fill") -> colnames(RCR); rm(name)
  
  rcr_chrom <- subset(empty_windows, empty_windows$chr == paste("chr",k,sep=""))
  rcr_chrom$n24_anubis <- NA
  rcr_chrom$length_used <- NA
   
  for (i in 1:nrow(rcr_chrom)) {
    
    subset(RCR, RCR$left_snp <= rcr_chrom$end[i] & RCR$right_snp > rcr_chrom$start[i]) -> tmp2
    tmp2$left_snp[tmp2$left_snp < rcr_chrom$start[i]] <- rcr_chrom$start[i]
    tmp2$right_snp[tmp2$right_snp > rcr_chrom$end[i]] <- rcr_chrom$end[i]
    tmp2$l <- tmp2$right_snp - tmp2$left_snp
    rcr_chrom$length_used[i] <- sum(tmp2$l)
    rcr_chrom$n24_anubis[i] <- sum(tmp2$mean*tmp2$l)/sum(tmp2$l); rm(tmp2)
  }; rm(RCR,i)
  
  print(c(nrow(rcr_chrom),"chrom", k))
  
  rbind(rcr,rcr_chrom) -> rcr; rm(rcr_chrom)
}; rm(k)

rm(empty_windows, wind)
save(rcr, file="for_pedigree_trios_250kbwin_recombination.Rd")

print("done")
