#!/bin/env Rscript

# Script for calculating the number of ancestry informative markers in given genomic windows across the genome

# Load R libraries
library(dplyr)

# Load R data file containing positions data frame generated by run.01.prep_for_pedigree_inconsistencies.R
load("local_ancestry_pedigree_trios_maskedSNPRCref.Rd", verbose=T)

# We only need the positions data frame so remove the other three data frames that were downloaded
rm(indiv_list, tracts2, trios)

# Load ALL ancestry calls on focal chromosome in Amboseli individuals (these are not unique ancestry informative markers - multiple rows can have the same ancestry informative marker but called in different individuals)
calls <- read.table("aims_maskedSNPRCref_CHROMOSOME.txt", header=F)
colnames(calls) <-  c("chrom", "AIM", "ancestry_call", "indiv", "n", "mode", "n_mode", "perc")

# Get unique ancestry informative markers
calls_unique <- distinct(calls, AIM)

# Get list of positions we're focusing on from focal chromosome
tmp <- positions[positions$chrom=="chrCHROMOSOME",]

print(nrow(tmp)) # print the number of positions we'll evaluate for the focal chromosome

# Count the number of ancestry informative markers in genomic windows defined by the size variable surrounding each position
# Define window size
size=35000 # use 35 kb as our window size because this is the same window used for calling ancestry in LCLAE 

tmp$start_window <- tmp$pos-(size/2) # define starting position of the genomic window
tmp$end_window <- tmp$pos+(size/2) # define ending position of the genomic window

# We'll store our results in the tmp data frame so define the results columns
tmp$AIM_count <- NA # make column where the unique number of ancestry informative markers will be put
tmp$total_calls_population <- NA # make column where the total number of ancestry calls across the Amboseli population in the given genomic window will be put
tmp$mean_calls_per_AIM <- NA # make column where the mean number of ancestry calls per AIM (across the Amboseli population) will be put
tmp$sd_calls <- NA # make column where the mean number of ancestry calls per AIM (across the Amboseli population) will be put

for (i in 1:nrow(tmp)) { # For each position/genomic window on the focal chromosome
   
   tmp2 <- tmp[i,] # grab the first row from the tmp data frame

   # first, let's look at unique ancestry informative markers
   tmp3 <- subset(calls_unique, AIM>tmp2$start_window & AIM<tmp2$end_window) # retain any unique ancestry informative markers that fall within the genomic window (centered on focal position)
   tmp$AIM_count[i] <- nrow(tmp3) # add the number of unique ancestry informative markers in the genomic window (centered on the focal position) to the tmp data frame

   # second, let's look at all ancestry calls
   tmp4 <- subset(calls, AIM>tmp2$start_window & AIM<tmp2$end_window) # retain any unique ancestry informative markers that fall within the genomic window (centered on focal position)
   tmp$total_calls_population[i] <- nrow(tmp4) # add the total number of ancestry calls across all ancestry informative markers in the genomic window

   tmp5 <- tmp4 %>% group_by(AIM) %>% summarize(count=n()) # count the number of ancestry calls across individuals per ancestry informative marker

if (nrow(tmp5)>0) { # assuming we have at least one ancestry informative marker

   tmp$mean_calls_per_AIM[i] <- mean(tmp5$count) # add the mean number of ancestry calls across individuals per ancestry informative marker across all ancestry informative markers in the genomic window
   tmp$sd_calls[i] <- sd(tmp5$count) # add the standard deviation of the number of ancestry calls across individuals per ancestry informative marker across all ancestry markers in the genomic window

}

   print(i) # print the number of the position/genomic window that was just finished

}

# These are the column names for the output tmp but we will leave column names out for now because we'll need to concatenate all chromosome files into one file at the end 
#colnames(qual3) <- c("chrom", "pos", "start_window", "end_window", "AIM_count", "total_calls_population", "mean_calls_per_AIM", "sd_calls")
write.table(tmp,file="for_pedigree_trios_AIM_count_maskedSNPRCref_pedigree_trios_chrCHROMOSOME.txt",quote=F,row.names=F, col.names=F)

print("done")
q(save="no")
